### ISSUE TITLE
trickle button - component completion

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-trickle#142] opened 2022-02-08 10:40 UTC
If using the trickle button, the block isn't complete until the trickle button has been clicked. This can cause issues in assessments as described here:
https://github.com/adaptlearning/adapt-contrib-assessment/issues/151

**Comment by oliverfoster** [comment] 2022-03-30 12:58
duplicate of https://github.com/adaptlearning/adapt-contrib-assessment/issues/151

**Closed by oliverfoster** 2022-03-30 12:58 UTC
Labels: bug
